#!/bin/bash

# unnecessary since notebook>5.3
# jupyter nbextension enable --py widgetsnbextension

jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
